# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_born', models.DateField()),
                ('author_origin', models.CharField(max_length=50)),
                ('published_till_now', models.ManyToManyField(to='Article.New_Article', verbose_name=b'Articles')),
            ],
        ),
    ]
