# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_author_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_detail',
            name='author_name',
        ),
    ]
