# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_remove_author_detail_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_detail',
            name='published_till_now',
        ),
        migrations.AddField(
            model_name='author_detail',
            name='published_till_now',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Article.New_Article', verbose_name=b'Articles'),
            preserve_default=False,
        ),
    ]
