# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_auto_20161003_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_detail',
            name='published_till_now',
        ),
        migrations.AddField(
            model_name='new_article',
            name='published_till_now',
            field=models.ManyToManyField(to='Article.Author_Detail', verbose_name=b'Articles'),
        ),
    ]
