# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_auto_20161003_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_detail',
            name='author_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
